### ISSUE TITLE
Miten ti-nspiren saa toimimaan winen avulla?

### ISSUE THREAD

**Issue by dtuukkanen** [digabi/digabi-os#105]
Tiedän, että tämä ei kuulu tänne, mutta haluaisin kuitenkin tietää vastauksen tähän kysymykseen. Mitä tiedostoja tarvitsen ja miten lisenssikoodin syöttämisen voi ohittaa(itselläni on kyllä lisenssi).

**Comment by mplattu** [comment]
YTL saa TI:ltä valmiin Linuxissa toimivan ohjelmistopaketin, jonka asennamme Abittiin. En pysty vastaamaan tähän kysymykseen.
