### ISSUE TITLE
Disable the annoying beep sound entirely

### ISSUE THREAD

**Issue by jonnelafin** [digabi/digabi-os#110]
A loud beep can currently be triggered by pressing an invalid key in some programs. This is really annoying and distracting for everyone in an exam situation. The beep can be really loud.

This could be done by unloading or blacklisting the pcspkr kernel module entirely, as I don't think it has any valid usecases in an exam environment anyways.

**Comment by developerfromjokela** [comment]
Fixed in #107

**Comment by jonnelafin** [comment]
Nice!
