### ISSUE TITLE
GPLv3 License Violation of Conveyed Software

### ISSUE THREAD

**Issue by JeppeX** [digabi/digabi-os#113]
I have noticed that your work Digabi-OS that is commonly provided as [Abitti](https://www.abitti.fi/fi/paivitykset/) contains numerous occurrences of GPL-licensed software. GPL license demands that all derivatives of GPL-licensed work (referred to as "covered works" by the license) including works that contain unmodified GPL-software _must only_ be redistributed under the conditions stated in the license. Of course this doesn't apply if your work passes the threshold of originality since then you would be the copyright holder, but currently you are distributing someone else's GPL-software so you have to oblige by the license given or you will be guilty of copyright infringement.

 **The violation:**

[GPLv3 license's subsection 6](https://www.gnu.org/licenses/gpl-3.0.en.html#section6) states the conditions for conveying non-source forms of covered works (compiled software, e.g. GIMP or Digabi-OS):

"_You may convey a covered work in object code form under the terms of sections 4 and 5, provided that you **also convey** the machine-readable **Corresponding Source** under the terms of this License,  in one of these ways: - -_"

You should read the permitted ways of distribution (paragraphs a through e, d especially as it applies to this case). All of them require you to either provide the source code or a written offer to provide the source code. [Evidently](https://www.abitti.fi/fi/paivitykset/) you are currently doing neither. This is a violation of the license.

I have read from issue #98 that you have supposedly offered to send the source code by letters (???). This is NOT a solution to this issue, as it is not permitted by the applicable paragraph d of subsection 6. EVEN if you started providing Abitti in physical form (usb-sticks) the conditions require the source code to be conveyed "_fixed on a durable physical medium customarily used for software interchange._" To my information letters are not such a medium.

**To the maintainers:**

If this matter isn't handled appropriately within a reasonable time window (source code provided in accordance to the GPL subsection 6), I **_WILL_** inform all the relevant copyright holders about this matter. There exists free software oriented NGOs that provide attorneys to represent copyleft license breach victims, so I would recommend carefully considering the possibility of a lawsuit taking into account that your work is used in the Finnish equivalent of A-levels.

However, if you and your experts still firmly believe that no violation has taken place, you need not to do anything. Though if possible, I would like to receive an ample explanation why.

PS: Oddly enough you have acquired licenses from closed source software owners. This is the correct way to handle copyright matters. To **ask** for permission to use someone's work. Of course you could ask a special license from all these [652](https://gist.github.com/JeppeX/5ee354ab31e7aa555199ee6d0e6eae6a) packages' copyright holders to avoid the obligations of GPL, but I highly doubt you would get them.

**Comment by Esinko** [comment]
As someone with plenty of intel about this subject: The letters were a joke (?) and the source code was provided via email to anyone who requested it. However, there is no official way to get the source code and you can't find the specific YTL employees personal email anywhere on the web.
So techincally when you jump through the hoops of finding the correct email address, you will be able to read the full sources. Thus there is no license violation.

**Comment by JeppeX** [comment]
I meant to say earlier in my post "All of them require you to either provide the source code or a written offer to provide the source code **[alongside with the product (Digabi-OS)]**." I also recommend anyone interested in this thread to read the same materials I recommend for maintainers. In this case paragraphs a through e of [subsection 6](https://www.gnu.org/licenses/gpl-3.0.en.html#section6). Currently YTL is distributes Abitti from a webpage, which puts their distribution method under paragraph d:

_d) Convey the object code by offering access from a designated place (gratis or for a charge), **and offer equivalent access to the Corresponding Source in the same way** through the same place at no further charge. You need not require recipients to copy the Corresponding Source along with the object code. If the place to copy the object code is a network server, the Corresponding Source may be on a different server (operated by you or a third party) that supports equivalent copying facilities, **provided you maintain clear directions next to the object code saying where to find the Corresponding Source. Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.**_

I have **highlighted** the parts that are currently being violated. I would also like to remind that GPL was crafted for the purpose of producing free software. That is, users are able to examine and modify the code etc, etc... The license is currently on version 3 because the earlier licenses contained loopholes. (Yes, sending source code by letters was possible under GPLv1.)

My point is that FSF has poured a notable amount of work on this license to protect this kind of ideology, and even if one was the kind of person to use someone's work against their values, there almost surely isn't a way to do so.

**Comment by Esinko** [comment]
I doubt this issue will even be read by YTL, as they seem to be already working on a full replacement exam system. All and all I wish you good luck in your quest @JeppeX :p
Keep us posted if you are contacted directly.

**Comment by JeppeX** [comment]
It has been almost a week now and we haven't got any response. For everyone's information, I have contacted YTL by email the same day I posted this issue. I think it is safe to say they have received the message and then for some reason or another decided not to respond (at least yet).

I wanted this issue to be resolved as easily as possible, but it seems I need to pass the ball to the copyright holders since it seems that YTL won't pay attention otherwise. I highly doubt that they would ignore major copyright holders such as Free Software Foundation, so I will now start drafting an email for the holders and **will send it on Friday (3.6.) 23:59 if we don't hear from the maintainers by that time**.

[For the copyright holders to better pursue the matter, the letter must provide as many details as possible about the case.](https://www.gnu.org/licenses/gpl-violation.html) Alongside the violations listed in this thread, I would also like to address the already available source code to avoid misunderstandings with the holders. @Esinko you wrote earlier that you know plenty about this subject, so would it be possible if you could give me a brief summary what is or is not open sourced by YTL? I know that at least the examinee monitoring software (e.g. `koe-nsa`) is closed source. And then there is the YTL's claim in the README that this isn't a open source project but the more details the better.

**Comment by Esinko** [comment]
> It has been almost a week now and we haven't got any response. For everyone's information, I have contacted YTL by email the same day I posted this issue. I think it is safe to say they have received the message and then for some reason or another decided not to respond (at least yet).
> 
> I wanted this issue to be resolved as easily as possible, but it seems I need to pass the ball to the copyright holders since it seems that YTL won't pay attention otherwise. I highly doubt that they would ignore major copyright holders such as Free Software Foundation, so I will now start drafting an email for the holders and **will send it on Friday (3.6.) 23:59 if we don't hear from the maintainers by that time**.
> 
> [For the copyright holders to better pursue the matter, the letter must provide as many details as possible about the case.](https://www.gnu.org/licenses/gpl-violation.html) Alongside the violations listed in this thread, I would also like to address the already available source code to avoid misunderstandings with the holders. @Esinko you wrote earlier that you know plenty about this subject, so would it be possible if you could give me a brief summary what is or is not open sourced by YTL? I know that at least the examinee monitoring software (e.g. `koe-nsa`) is closed source. And then there is the YTL's claim in the README that this isn't a open source project but the more details the better.

Please contact me via Discord on Testausserveri ry's server. Join [from here](https://discord.gg/testaus).
Ping `@Esinko#7976` and we can schedule a virtual meeting there.

**Comment by JeppeX** [comment]
I have managed to contact the maintainers. After a long discussion about the matter they are claiming that Digabi-OS and the examination software are two independent programs and therefore constitute an "aggregate" as defined in the section 5 of the license. I strongly disagree with this interpretation: The examination software is built/working ONLY on Digabi-OS. The OS is also built in such a way that indicates its purpose solely to be environment to run examination software in. The software cannot run in other environments because it assumes things that are true/present only in Digabi-OS, so the examination software is therefore by nature an extension or part of the Digabi-OS.

I will now pass the ball to the copyright holders and hope that they will pursue this matter further.

PS: They aren't even complying with the license on Digabi-OS. There is no link to this repo on the distribution site.

**Comment by mplattu** [comment]
Closing this issue as the opener has already documented his disappointment with our interpretation of the license issue.

**Comment by JeppeX** [comment]
@mplattu Just so you know even if the work was to be an aggregate you are still violating license:

- Link to this repo is missing from the distribution site.
- This "separate" disk image cannot be built due to references to private repos.

IMO the latter is pretty strong evidence that the works aren't separate but that is left for you and the copyright holders to sort out. I've only contacted FSF so far since their policy is to try negotiating first.
