### ISSUE TITLE
Tiny text on huge resolutions (Retina / HiDPI)

### ISSUE THREAD

**Issue by ypcs** [digabi/digabi-os#40]
User-submitted report: ~3200x1800 resolution => text is too small to read. We should do better scaling automatically.

**Comment by developerfromjokela** [comment]
The Hi-DPI is imperfect, and does not scale in ie. NSpire, and the taskbar is still small.

Let's take for example, Linux Mint. The Hi-DPI really works in mint, and it does scale in almost all applications. Current method of Hi-DPI in Abitti does not work correctly. I would recommend re-opening this issue.
