### ISSUE TITLE
System time changed by digabi

### ISSUE THREAD

**Issue by Jaakkonen** [digabi/digabi-os#80]
With kernel 4.19-rc7 the system seems to sometimes update system time to windows-like local time.
This ~~fucks up~~ annoys some Linux people as they need to reset the system time to the proper UTC one after usage of digabi. (This seems to happen only some times)
Instructions to reproduce:
1. Set system time to UTC
2. Boot to digabi/abitti
3. Shut down
4. Open your own OS and see time broken

I propose a fix could be to check if time is UTC and not changing it then?

**Comment by hsalokor** [comment]
This should be fixed in latest release, i.e. Abitti should no longer modify BIOS clock.

**Comment by timotm** [comment]
https://www.abitti.fi/fi/paivitykset/parannukset/digabios-palvelintikku-opiskelijan-tikku/
> 7.11.2018 (113) versio ABITTI18457 (opiskelijan tikku)
>  Korjattu: Opiskelijan koneen kellonaikaa ei talleteta rautakelloon.
