### ISSUE TITLE
Support for the latest Intel wireless Wifi / Wlan drivers

### ISSUE THREAD

**Issue by o-p-v** [digabi/digabi-os#99]
Please, include also support for the latest Intel wireless firmware drivers for

- Intel® Wi-Fi 6 AX201 (iwlwifi-Qu)
- Intel® Wi-Fi 6 AX200 (iwlwifi-cc)

See more information and guidelines from
- https://www.intel.com/content/www/us/en/support/articles/000005511/network-and-i-o/wireless.html
- https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi
- https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/

**Comment by mplattu** [comment]
Please try the Buster beta, see https://www.abitti.fi/blogi/2020/10/uusi-abitti-versio-beta-testikaytossa/

**Comment by o-p-v** [comment]
Wifi drivers seems to work now with Debian Buster based on version.
Tested using by Asus Zenbook 14 UX425 Pure 3 laptop version.
Thanks!
